In [2]:
import numpy as np
np.__version__

'1.15.1'

In [3]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.full((3,5), 1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
x1=np.array([4,3,4,4,8,4])
print (x1)

[4 3 4 4 8 4]


In [18]:
x1[4]

8

In [23]:
x2 = np.random.randint(10, size=(3,4))
print (x2)

[[7 9 4 5]
 [7 6 2 1]
 [9 7 9 4]]


In [24]:
x2[1,2]

2

In [26]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[:5]

array([0, 1, 2, 3, 4])

In [28]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [29]:
x[2:6]

array([2, 3, 4, 5])

In [30]:
x=np.array([1,2,3,4])
y=np.array([4,3,2,1])
z=[21,21,21]
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  4,  3,  2,  1, 21, 21, 21])

In [32]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
x=np.array([3,4,5])
grid=np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [37]:
z=np.array([9],[9])
np.hstack([grid,z])

TypeError: data type not understood

In [38]:
import pandas as pd

In [39]:
data =pd.DataFrame({'Country':['IND','AUS','USA','JAPAN','Chi'], 'Rank':[121,40,100,130,11]})
data

Country  Rank
0     IND   121
1     AUS    40
2     USA   100
3   JAPAN   130
4     Chi    11

In [40]:
data.describe()

Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Rank       5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [44]:
data = pd.DataFrame({'Group':['a','a','a','b','b','b','c','c','c'], 'Value':[4,3,12,6,7.5,8,3,5,6]})
data

Group  Value
0     a    4.0
1     a    3.0
2     a   12.0
3     b    6.0
4     b    7.5
5     b    8.0
6     c    3.0
7     c    5.0
8     c    6.0

In [48]:
data.sort_values(by=['Value'],ascending=True)

Group  Value
1     a    3.0
6     c    3.0
0     a    4.0
7     c    5.0
3     b    6.0
8     c    6.0
4     b    7.5
5     b    8.0
2     a   12.0

In [50]:
data.sort_values(by=['Group','Value'],ascending=[True, False])

Group  Value
2     a   12.0
0     a    4.0
1     a    3.0
5     b    8.0
4     b    7.5
3     b    6.0
8     c    6.0
7     c    5.0
6     c    3.0

In [51]:
data = pd.DataFrame({'K1':['One']*3 + ['Two']*4, 'K2':[3,2,1,3,3,4,4]})
data

K1  K2
0  One   3
1  One   2
2  One   1
3  Two   3
4  Two   3
5  Two   4
6  Two   4

In [52]:
data.sort_values(by=['K2'])

K1  K2
2  One   1
1  One   2
0  One   3
3  Two   3
4  Two   3
5  Two   4
6  Two   4

In [54]:
data.drop_duplicates()

K1  K2
0  One   3
1  One   2
2  One   1
3  Two   3
5  Two   4